# For machine specific settings create a config in `~/.config/mise.toml`
[tools]
bun = "latest"
chezmoi = "latest"
go = "latest"
node = "26"
pnpm = "latest"
prek = "latest"
python = "latest"
terraform = "latest"
tf-summarize = "latest"
tflint = "latest"
uv = "latest"
yq = "latest"
"pipx:pynvim" = "latest"
aws-cli = "latest"
ansible-core = "latest"
semgrep = "latest"
yazi = "latest"

[settings]
activate_aggressive = true
experimental = true
lockfile = true
pin = true
idiomatic_version_file = true
idiomatic_version_file_enable_tools = [
  "bun",
  "go",
  "node",
  "pnpm",
  "python",
  "terraform",
  "tflint",
  "uv",
  "yq",
]
github.github_attestations = true
node.corepack = true
python.uv_venv_auto = "create|source"
pipx.uvx = true
slsa = true
