# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  border: single
  showBottomLine: false
  showPanelJumps: false
  skipAmendWarning: true
  skipRewordInEditorWarning: true
  showRootItemInFileTree: false
  theme:
    activeBorderColor: ["#31748f", bold]
    inactiveBorderColor: ["#6e6a86"]
    searchingActiveBorderColor: ["#ebbcba", bold]
    optionsTextColor: ["#9ccfd8"]
    selectedLineBgColor: ["#31748f"]
    inactiveViewSelectedLineBgColor: ["#26233a", bold]
    cherryPickedCommitFgColor: ["#1f1d2e"]
    cherryPickedCommitBgColor: ["#ebbcba"]
    markedBaseCommitFgColor: ["#9ccfd8"]
    markedBaseCommitBgColor: ["#f6c177"]
    unstagedChangesColor: ["#eb6f92"]
    defaultFgColor: ["#e0def4"]
git:
  overrideGpg: true
os:
  editPreset: nvim
  editInTerminal: true
  edit: "if [ -n \"$NVIM\" ]; then nvim --server $NVIM --remote-send '<C-\\><C-n><cmd>close<cr>' && nvim --server $NVIM --remote {{filename}}; else nvim {{filename}}; fi"
notARepository: quit
promptToReturnFromSubprocess: false
customCommands:
  - key: "<c-g>"
    context: files
    description: Generate commit message with qwen
    loadingText: Generating commit message...
    command: |
      git diff --cached | mlx_lm.generate --verbose False \
      --model mlx-community/Qwen3-14B-4bit \
      --prompt "/no_think Generate a concise conventional commit message in lowercase for the following git diff. Output only the commit message:

      $(git diff --cached)" \
        | tail -n 1 \
        | git commit -F -
