# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  border: single
  showBottomLine: false
  showPanelJumps: false
  skipAmendWarning: true
  skipRewordInEditorWarning: true
  theme:
    activeBorderColor: ["#31748f", bold]
    inactiveBorderColor: ["#6e6a86"]
    searchingActiveBorderColor: ["#ebbcba", bold]
    optionsTextColor: ["#9ccfd8"]
    selectedLineBgColor: ["#31748f"]
    inactiveViewSelectedLineBgColor: ["#26233a", bold]
    cherryPickedCommitFgColor: ["#1f1d2e"]
    cherryPickedCommitBgColor: ["#ebbcba"]
    markedBaseCommitFgColor: ["#9ccfd8"]
    markedBaseCommitBgColor: ["#f6c177"]
    unstagedChangesColor: ["#eb6f92"]
    defaultFgColor: ["#e0def4"]
git:
  overrideGpg: true
  # pagers:
  #   - externalDiffCommand: "difft --color=always --display=inline --syntax-highlight=on --tab-width=2"
notARepository: quit
promptToReturnFromSubprocess: false
