clean:
    nix-store --gc

deepClean:
    nix-collect-garbage -d --delete-older-than 1d

linux profile:
   nix run .#homeConfigurations.{{profile}}.activationPackage

update:
    nix flake update

optimise:
    nix-store --optimise
