# For machine specific settings create a config in `~/.config/mise.toml`
[tools]
"pipx:pynvim" = "latest"
"github:alltuner/mise-completions-sync" = "latest"
ansible-core = "latest"
aws-cli = "latest"
bat = "latest"
bun = "latest"
dive = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
go = "latest"
gum = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "26"
pnpm = "latest"
prek = "latest"
process-compose = "latest"
python = "latest"
ripgrep = "latest"
semgrep = "latest"
skate = "latest"
starship = "latest"
terraform = "latest"
tf-summarize = "latest"
tflint = "latest"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
yazi = "latest"
yq = "latest"

[settings]
activate_aggressive = true
experimental = true
lockfile = true
pin = true
idiomatic_version_file = true
idiomatic_version_file_enable_tools = ["bun", "go", "node", "pnpm", "python", "terraform", "uv"]
github.github_attestations = true
node.corepack = true
python.uv_venv_auto = "create|source"
pipx.uvx = true
slsa = true

[hooks]
postinstall = "misecompsync --shell zsh"
